const municipiosColombia = [
    "Acacías",
    "Aguachica",
    "Alcalá",
    "Anapoima",
    "Aranzazu",
    "Arboletes",
    "Armenia",
    "Baranoa",
    "Barranquilla",
    "Bello",
    "Bogotá",
    "Bucaramanga",
    "Buenaventura",
    "Cali",
    "Cartagena",
    "Cartago",
    "Caucasia",
    "Ciénaga",
    "Cúcuta",
    "Dosquebradas",
    "Duitama",
    "Envigado",
    "Florencia",
    "Floridablanca",
    "Fusagasugá",
    "Girardot",
    "Girón",
    "Ibagué",
    "Ipiales",
    "Itagüí",
    "Jamundí",
    "La Dorada",
    "La Estrella",
    "La Virginia",
    "Leticia",
    "Los Patios",
    "Madrid",
    "Magangué",
    "Maicao",
    "Manizales",
    "Medellín",
    "Montería",
    "Neiva",
    "Palmira",
    "Pamplona",
    "Pasto",
    "Pereira",
    "Piedecuesta",
    "Popayán",
    "Puerto Asís",
    "Puerto Boyacá",
    "Puerto Tejada",
    "Quibdó",
    "Riohacha",
    "Rionegro",
    "Sabanalarga",
    "Sabaneta",
    "Sahagún",
    "San Andrés",
    "San José del Guaviare",
    "Santa Marta",
    "Sincelejo",
    "Soacha",
    "Sogamoso",
    "Soledad",
    "Tuluá",
    "Tunja",
    "Turbo",
    "Valledupar",
    "Villavicencio",
    "Yopal",
    "Zipaquirá"
];